version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: user
        uid: 1000
    container_name: hicaliber-app
    image: hicaliber
    command: /usr/local/bin/app-entry
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      CONTAINER_MODE: dev
    volumes:
      - ./:/var/www
      - ./.docker-compose/app/app-entry.sh:/usr/local/bin/app-entry
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z 127.0.0.1 8080" ]
      interval: 10s
      timeout: 3s
      retries: 30
    networks:
      - hicaliber-network
  caddy:
    image: caddy:latest
    container_name: hicaliber-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker-compose/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - hicaliber-network
    depends_on:
      app:
        condition: service_healthy
  redis:
    image: redis:alpine
    container_name: hicaliber-redis
    restart: unless-stopped
    command: redis-server --save 20 1 --logLevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - hicaliber-network

  db:
    image: mysql:8.0
    container_name: hicaliber-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hicaliber-network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  hicaliber-network:
    driver: bridge
